### ISSUE TITLE
handle better monitoring repo

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#202] opened 2019-09-26 13:37 UTC
Right now the monitoring repo is hardcode to salt 
https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/monitoring/init.sls#L3

we should use a variable like the ha-factory repo.

Perhaps we should condensate this both 2 vars in a list. (@diegoakechi @stefanotorresi @arbulu89 @ayoub-belarbi )

I think personally having 2 variables, preserving the ha-factory repo and adding the monitoring repo is OK, but i'm ok to have a list also

**Comment by stefanotorresi** [comment] 2019-09-26 15:38
I'm not sure: one could still customise the pillars to change this, so I don't see a that bad as it stands.

**Comment by MalloZup** [comment] 2019-09-26 15:48
the problem right now is that the repository is hardcoded to SLE15 sytstems. The repo should vary for os . Like if you have another system we will always inject that repo

**Comment by ayoub-belarbi** [comment] 2019-09-27 10:33
I agree, it should be dynamic and we shouldn't do it this way.. the easiest solution will be having a separate var for now, the optimal solution will be having the packages in Package Hub!

**Comment by stefanotorresi** [comment] 2019-09-27 10:40
> The repo should vary for os
Oh, okay! Should all the repos match the same OS version, then?

In any case, a map of `package -> repo` sounds the nicest way to do this, it leaves the door open for extension without modifying existing code.

**Comment by arbulu89** [comment] 2019-09-30 15:32
Closing! The issue is solved after the last PR

**Closed by arbulu89** 2019-09-30 15:32 UTC
Labels: monitoring
