### ISSUE TITLE
Document requirements for GCP deployments

### ISSUE THREAD

**Issue by zmarano** [SUSE/ha-sap-terraform-deployments#248] opened 2019-11-08 16:31 UTC
GCP deployments in this terraform repo are only for BYOS. Many users are attempting to use these templates with on demand SLES instances and running into failures with registration.

@rjschwei can provide some more details about impact.

**Comment by MalloZup** [comment] 2019-11-08 17:41
@zmarano thx.  We would be glad to have more details on this and how to reproduce in order to fix the behaviour. thx for the issue and time.

**Comment by zmarano** [comment] 2019-11-08 17:53
The actual problem is that SUSEConnect conflicts with registercloudguest (which is what is used to give SLES instances access to SLES content in the on demand instance case. The terraform templates here all assume BYOS and therefore SUSEConnect. We have seen a number of users use these templates and treat the resulting instances as on demand without understanding that what they created were BYOS instances. @rjschwei can explain the bad things that happen when these two things collide better than I can.

In the end, these templates should be able to support either BYOS or on demand. But at the very least, we should just document what they are doing now.

**Comment by diegoakechi** [comment] 2019-11-12 12:42
@zmarano  Thanks for reporting this. We have identified this too, and this PR should solve this issue: https://github.com/SUSE/ha-sap-terraform-deployments/pull/245. It should be merged soon...

**Comment by arbulu89** [comment] 2019-11-13 09:20
Hi @zmarano ,
We merged the PR with the fix for Azure, that should work for GCP too.
Could you check if this fixes your issues?

**Comment by ikapelyukhin** [comment] 2019-11-20 15:51
@arbulu89 please let me know if you need any assistance with `registercloudguest`, `SUSEConnect` or any other registration-related things on on-demand instances.

**Comment by arbulu89** [comment] 2019-11-20 16:14
> @arbulu89 please let me know if you need any assistance with `registercloudguest`, `SUSEConnect` or any other registration-related things on on-demand instances.

Hi @ikapelyukhin ,
The truth is that this particular issue was not related to `registercloudguest`. It was our own issue that we were not considering correctly `BYOS` and `non BYOS` images. This is fixed now.

Anyway, now you ask, I found some issues during deployments in Azure with terraform with `non BYOS` images where the OS was not correctly registered. This is the `/var/log/cloudregister` initial content:
```
cloudadmin@dev03-hana02:~> cat /var/log/cloudregister
2019-11-12 12:16:17,701 INFO:Using API: regionInfo
2019-11-12 12:16:17,702 INFO:Using region server: 40.121.202.140
2019-11-12 12:16:17,771 INFO:Starting new HTTPS connection (1): 40.121.202.140
2019-11-12 12:16:17,772 ERROR:No response from: 40.121.202.140
2019-11-12 12:16:17,772 INFO:Using region server: 52.187.53.250
2019-11-12 12:16:17,773 INFO:Starting new HTTPS connection (1): 52.187.53.250
2019-11-12 12:16:17,774 ERROR:No response from: 52.187.53.250
2019-11-12 12:16:17,774 INFO:Using region server: 52.233.155.246
2019-11-12 12:16:17,775 INFO:Starting new HTTPS connection (1): 52.233.155.246
2019-11-12 12:16:17,775 ERROR:No response from: 52.233.155.246
2019-11-12 12:16:17,775 ERROR:None of the servers responded
2019-11-12 12:16:17,775 ERROR:	Attempted: ['40.121.202.140', '52.187.53.250', '52.233.155.246']
2019-11-12 12:16:17,775 ERROR:Exiting without registration
```

Anyway, I repeat that this is not related to this issue in particular.

**Comment by ikapelyukhin** [comment] 2019-11-20 16:30
> Anyway, now you ask, I found some issues during deployments in Azure with terraform with `non BYOS` images where the OS was not correctly registered. This is the `/var/log/cloudregister` initial content:

This looks to be caused by networking issues -- seems like none of the registration servers are reachable. On-demand instances run `guestregister.service` on boot to obtain a registration, if the network isn't reachable at this time -- registration fails. (Can be attempted again by manually re-running `guestregister.service` or `registercloudguest` or even rebooting the instance).

**Comment by rjschwei** [comment] 2019-11-20 16:42
Note that "network not reachable"  in this context means the Internet is not reachable. The update infrastructure for on-demand instances is currently only reachable over the Internet. IP addresses for the update infrastructure servers in various regions and frameworks can be found using `pint`

**Comment by arbulu89** [comment] 2019-11-21 09:54
Thanks @ikapelyukhin and @rjschwei , the worst thing is that it happens randomly... Not always.
We have created a workaround to fix that: https://github.com/SUSE/ha-sap-terraform-deployments/pull/245

I think, the initial issue is fixed now, so the unique missing piece is just testing.

**Comment by MalloZup** [comment] 2020-09-21 19:06
I do think we have fixed this. I have tested GCP. 

If we do have any more specific issue with GCP feel free to reopen a new issue

Thx guys! closing

**Closed by MalloZup** 2020-09-21 19:06 UTC
Labels: bug
