### ISSUE TITLE
GCP S/4HANA deployment failure

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#683] opened 2021-04-22 15:59 UTC
**Used cloud platform**
GCP

**Used SLES4SAP version**
SLES15SP2 for SAP Applications 

**Used client machine OS**
SLES15SP2

**Expected behaviour vs observed behaviour**
The expected delivery is a successful S/4HANA deployment but it was failed

**How to reproduce**
1. Use S/4HANA 1909.
2. Use the default S/4HANA Terraform configurations
3. Deploy the environment, as usual, using `terrafrom init`, `terraform plan`, and `terraform apply --auto-approve` commands.
4. I had the following deployment error messages:
```
module.netweaver_node.module.netweaver_provision.null_resource.provision[2] (remote-exec): Thu Apr 22 13:54:44 UTC 2021::demo1-netweaver03::[ERROR] deployment failed 
Error: error executing "/tmp/terraform_1501732074.sh": Process exited with status 1
```

**Troubleshooting**
1. SAP HANA HA cluster deployment was completed successfully.
2. The DRBD HA cluster deployment was completed successfully. 
3. The S/4HANA deployment was failed.
4.  Even if the NFS shares were exported to the ASCS and ERS nodes, `sapcontrol` command was not found. 
```
demo1-netweaver01:~ # df -ht nfs4
Filesystem                Size  Used Avail Use% Mounted on
10.0.1.22:/HA1/sapmnt      10G   42M   10G   1% /sapmnt
10.0.1.22:/HA1/usrsapsys   10G   42M   10G   1% /usr/sap/HA1/SYS
10.0.1.22:/HA1/ASCS        10G   42M   10G   1% /usr/sap/HA1/ASCS00
```
```
demo1-netweaver01:~ # su - ha1adm
demo1-netweaver01 /home/ha1adm% sapcontrol -nr 00 -function GetProcessList
sapcontrol: Command not found.
```
5. The NFS shares have no files:
```
demo1-netweaver01:~ # ls /sapmnt/ /usr/sap/HA1/SYS/ /usr/sap/HA1/ASCS00/
/sapmnt/:

/usr/sap/HA1/ASCS00/:

/usr/sap/HA1/SYS/:
``` 
6. The ASCS and ERS resource agents were not running due to the `sapcontrol` commands issue:
```
demo1-netweaver01:~ # crm resource status rsc_sap_HA1_ASCS00 rsc_sap_HA1_ERS10
resource rsc_sap_HA1_ASCS00 is NOT running
resource rsc_sap_HA1_ERS10 is NOT running
```

Best regards,
Ab

**Comment by ab-mohamed** [comment] 2021-04-22 18:50
`sapinst.log` log file reports errors regarding using the master password, but I have already set the master password as it is shown in the `terraform.tfvars` file:
```
INFO 2021-04-22 12:45:46.439 (root/sapinst)
Execute step askMasterPwd of component |NW_ABAP_ASCS|ind|ind|ind|ind|0|0|NW_GetSidNoProfiles|ind|ind|ind|ind|getSid|0|NW_GetUserParameter|ind|ind|ind|ind|users|0|NW_GetMasterPassword|ind|ind|ind|ind|masterpwd|0

ERROR 2021-04-22 12:45:46.582 (root/sapinst) id=modlib.jslib.caughtException errno=MUT-03025
Caught ESAPinstException in module call: Validator of step '|NW_ABAP_ASCS|ind|ind|ind|ind|0|0|NW_GetSidNoProfiles|ind|ind|ind|ind|getSid|0|NW_GetUserParameter|ind|ind|ind|ind|users|0|NW_GetMasterPassword|ind|ind|ind|ind|masterpwd|0|askMasterPwd' reported an error:
Start SAPinst in interactive mode to solve this problem.
[...]

ERROR 2021-04-22 12:45:46.662 (root/sapinst) id=controller.stepExecuted errno=FCO-00011
The step askMasterPwd with step key |NW_ABAP_ASCS|ind|ind|ind|ind|0|0|NW_GetSidNoProfiles|ind|ind|ind|ind|getSid|0|NW_GetUserParameter|ind|ind|ind|ind|users|0|NW_GetMasterPassword|ind|ind|ind|ind|masterpwd|0|askMasterPwd was executed with status ERROR (Last error reported by the step: Caught ESAPinstException in module call: Validator of step '|NW_ABAP_ASCS|ind|ind|ind|ind|0|0|NW_GetSidNoProfiles|ind|ind|ind|ind|getSid|0|NW_GetUserParameter|ind|ind|ind|ind|users|0|NW_GetMasterPassword|ind|ind|ind|ind|masterpwd|0|askMasterPwd' reported an error:
Start SAPinst in interactive mode to solve this problem.
```

**Comment by busetde** [comment] 2021-04-24 00:49
Hi @ab-mohamed,

Thanks for rising the issues for S/4HANA 1909 on GCP.
I can confirm the same issues happened with my environment as well.

Look forward for the resolution.

Thanks - Budi

**Comment by arbulu89** [comment] 2021-04-26 10:05
Hey @ab-mohamed ,
I found this in the logs: 
```
Checking input element 'masterPwd': Value 'xxxxxxxx' is shorter than 10 characters.
```
Could you try with a 10 chars long password?
I don't know when they added this constraint, but this is what the logs report...

**Comment by busetde** [comment] 2021-04-26 14:27
Hi @ab-mohamed,

Have you succefully deployed the S/4HANA1909?

After set the password with min. 10 chars and less than 14 chars. 
The process went thru but got error in netweaver[3] as netweaver[2] can't completed it's process.

![image](https://user-images.githubusercontent.com/63712632/116099336-0f9b9a00-a6d6-11eb-9fcf-3260bc0608eb.png)


Thanks - Budi

**Comment by busetde** [comment] 2021-04-27 01:27
Hi @arbulu89,

I'm running the second test again for 1909 and the result still the same (netweaver[3] failed as netweaver[2] can't finished).
Please kindly find the attached salt* log and sapinst* log.

Thanks - Budi
[1909netweaver4.zip](https://github.com/SUSE/ha-sap-terraform-deployments/files/6381273/1909netweaver4.zip)
[1909netweaver3.zip](https://github.com/SUSE/ha-sap-terraform-deployments/files/6381274/1909netweaver3.zip)

**Comment by ab-mohamed** [comment] 2021-04-27 06:16
@arbulu89 @busetde : 

I confirm that using a 10 chars-long password resolved that issue. ASCS and ERS were deployed successfully, but it seems that the deployment must have the `IGSEXE` file in my bucket for the PAS and AAS servers, otherwise the two servers deployment will fail. 

```
WARNING    2021-04-26 14:29:52.081 (root/sapinst) (startInstallation) id=cdsrv.archiveCheckerStatus.furtherArchivesRequired com.sap.sdt.ins.component.archive_extraction.SpecifyArchive
The following archives are also required, otherwise, you cannot continue: "IGSEXE.SAR"
```

I will try to use the `IGSEXE` file for the 1909 kernel.

Is there any way to extract the S/4HANA files `S4CORE104_INST_EXPORT_*.zip` to have the `IGSEXE` file?

I tried using:
1. `SAPCAR` command:
```
# ./SAPCAR.EXE -xvf "S4CORE104_INST_EXPORT_*"
processing archive S4CORE104_INST_EXPORT_1.zip...
format error in header
```
2. `unzip` command but it did not work correctly. 

Best regards,
Ab

**Comment by ab-mohamed** [comment] 2021-04-27 06:21
@busetde 

Can you please check if your Databas is up and running? 

I see the following error messages in your log:
```
ERROR 2021-04-27 01:14:30.350 (root/sapinst) id=modlib.jslib.caughtException errno=MUT-03025
Caught ESAPinstException in module call: Validator of step '|NW_ABAP_CI|ind|ind|ind|ind|0|0|NW_GetSidFromProfilesPartial|ind|ind|ind|ind|getSid|0|NW_getDBInfo|ind|ind|ind|ind|db|0|NW_HDB_getDBInfo|ind|ind|ind|ind|hdb_dbinfo|0|getDBInfo' reported an error:
The database connection with database user SYSTEM cannot be set up. Check that the database is online and the password of user SYSTEM is correct.
Start SAPinst in interactive mode to solve this problem.

ERROR 2021-04-27 01:14:30.448 (root/sapinst) id=controller.stepExecuted errno=FCO-00011
The step getDBInfo with step key |NW_ABAP_CI|ind|ind|ind|ind|0|0|NW_GetSidFromProfilesPartial|ind|ind|ind|ind|getSid|0|NW_getDBInfo|ind|ind|ind|ind|db|0|NW_HDB_getDBInfo|ind|ind|ind|ind|hdb_dbinfo|0|getDBInfo was executed with status ERROR (Last error reported by the step: Caught ESAPinstException in module call: Validator of step '|NW_ABAP_CI|ind|ind|ind|ind|0|0|NW_GetSidFromProfilesPartial|ind|ind|ind|ind|getSid|0|NW_getDBInfo|ind|ind|ind|ind|db|0|NW_HDB_getDBInfo|ind|ind|ind|ind|hdb_dbinfo|0|getDBInfo' reported an error:
The database connection with database user SYSTEM cannot be set up. Check that the database is online and the password of user SYSTEM is correct.
Start SAPinst in interactive mode to solve this problem).
```

**Comment by busetde** [comment] 2021-04-27 08:45
Hi @ab-mohamed,

igsexe*.sar should included in the folder Kernel, same as SAPEXE, SAPEXEDB,...
It's ` igsexe_13-80003187.sar` in 1909

HANA database confirmed up and running.

Is there something to do with this log, haven't seen this log in 1809?
Any new parameter introduced with 1909?

`TRACE      2021-04-27 01:14:29.381 (root/sapinst) (startInstallation) [Installer Callback]
Write on stdin: DATABASE_SYSTEM_USER_PASSWORD=*

TRACE      2021-04-27 01:14:29.381 (root/sapinst) (startInstallation) [Installer Callback]
Write on stdin: SYSTEM_DATABASE_SYSTEM_USER_PASSWORD=*

TRACE      2021-04-27 01:14:30.253 (root/sapinst) (startInstallation) [syuxctask.cpp:466] CUnixProcessManager::sap_waitpid()
Child process 30010 returned 0


TRACE      2021-04-27 01:14:30.253 (root/sapinst) (startInstallation) [Installer Callback]
HDB return code of java call: 0

INFO       2021-04-27 01:14:30.255 (root/sapinst) (startInstallation) [syuxcfile.cpp:216] id=syslib.filesystem.removedFile CSyFileImpl::removeEx(ISyFSErrorHandler * pErrorHandler)
Removed file /tmp/swpm_unattended/HdbStdout.txt.

TRACE      2021-04-27 01:14:30.255 (root/sapinst) (startInstallation) [Installer Callback]
Connect successful: false`

Thanks - Budi

**Comment by ab-mohamed** [comment] 2021-04-28 05:43
@arbulu89 I redeployed the environment using `igsexe_13-80003187.sar` and I had the same deployment failure with the same log entries as in Budi's case: 
```
ERROR 2021-04-27 17:01:38.687 (root/sapinst) id=modlib.jslib.caughtException errno=MUT-03025
Caught ESAPinstException in module call: Validator of step '|NW_ABAP_CI|ind|ind|ind|ind|0|0|NW_GetSidFromProfilesPartial|ind|ind|ind|ind|getSid|0|NW_getDBInfo|ind|ind|ind|ind|db|0|NW_HDB_getDBInfo|ind|ind|ind|ind|hdb_dbinfo|0|getDBInfo' reported an error:
The database connection with database user SYSTEM cannot be set up. Check that the database is online and the password of user SYSTEM is correct.
Start SAPinst in interactive mode to solve this problem.

ERROR 2021-04-27 17:01:38.788 (root/sapinst) id=controller.stepExecuted errno=FCO-00011
The step getDBInfo with step key |NW_ABAP_CI|ind|ind|ind|ind|0|0|NW_GetSidFromProfilesPartial|ind|ind|ind|ind|getSid|0|NW_getDBInfo|ind|ind|ind|ind|db|0|NW_HDB_getDBInfo|ind|ind|ind|ind|hdb_dbinfo|0|getDBInfo was executed with status ERROR (Last error reported by the step: Caught ESAPinstException in module call: Validator of step '|NW_ABAP_CI|ind|ind|ind|ind|0|0|NW_GetSidFromProfilesPartial|ind|ind|ind|ind|getSid|0|NW_getDBInfo|ind|ind|ind|ind|db|0|NW_HDB_getDBInfo|ind|ind|ind|ind|hdb_dbinfo|0|getDBInfo' reported an error:
The database connection with database user SYSTEM cannot be set up. Check that the database is online and the password of user SYSTEM is correct.
Start SAPinst in interactive mode to solve this problem).
```

@busetde SAP PAM states that SAP kernel v7.77 is used with S/4HANA 1909. `igsexe_13-80003187.sar` belongs to SAP Kernel v7.53 and there is no `IGSEXE` file for the SAP Kernel v.77. 
 
The current problem could be related to the automation platform **or** the used `IGSEXE` version. 

Best regards,
Ab

**Comment by arbulu89** [comment] 2021-04-28 09:53
Hi @busetde @ab-mohamed 

In @busetde 's log file I can observe that the DB import failed before the PAS installation which can be the root source of the error:
```
Client received SOAP Fault from server: Cannot create protocol file Please see the server log to find more detail regarding exact cause of the failure..
```

I have not seen this before but I would start researching why this is happening in the 1st place

**Comment by ab-mohamed** [comment] 2021-04-28 09:55
Thank you @arbulu89. I have shared my logs with you also. :)

Best regards,
Ab

**Comment by arbulu89** [comment] 2021-04-28 10:03
@busetde @ab-mohamed 
To find out better what's going on let's do the next:
1. Edit the `pillar_examples/automatic/netweaver/netweaver.sls` and remove the `-host` entry for the PAS. You can just put a random string in the `host` value there. So you would have:

```
- host: foo
      virtual_host: sap{{ sid_lower }}pas
      virtual_host_interface: {{ virtual_host_interface }}
      virtual_host_mask: {{ virtual_host_mask }}
      ascs_virtual_host: sap{{ sid_lower }}as
      sid: {{ sid_upper }}
      instance: {{ '{:0>2}'.format(grains['pas_instance_number']) }}
      root_user: root
      root_password: linux
      sap_instance: pas
```
Instead of:
```
- host: {{ grains['name_prefix'] }}0{{ app_start_index+1 }}
      virtual_host: sap{{ sid_lower }}pas
      virtual_host_interface: {{ virtual_host_interface }}
      virtual_host_mask: {{ virtual_host_mask }}
      ascs_virtual_host: sap{{ sid_lower }}as
      sid: {{ sid_upper }}
      instance: {{ '{:0>2}'.format(grains['pas_instance_number']) }}
      root_user: root
      root_password: linux
      sap_instance: pas
```
**This is for the `pas` entry, check the `sap_instance`**

2. Repeat the deployment and send the same logs from `netweaver02` (the 3rd node). I need everything in `swpm_unnattended`, all the files.

Let's see if this gives some additional information.

We need to avoid the PAS installation as this overwrites the logs from previous executions (we might need to improve this to have all the instances logs...)

Thanks
Xabi

**Comment by busetde** [comment] 2021-04-28 13:04
Hi @arbulu89 ,

Please find attached the ```swpm_unattended``` in zip file with ```netweaver.sls``` modified.

Thanks - Budi
[swpm_unattended.zip](https://github.com/SUSE/ha-sap-terraform-deployments/files/6391954/swpm_unattended.zip)

**Comment by arbulu89** [comment] 2021-04-28 19:25
@busetde 
This test didn't work, the PAS execution has been executed. Are you sure you did the changes in the correct file?
Xabi

**Comment by busetde** [comment] 2021-04-29 01:21
Hi @arbulu89,

So have changed the ```netweaver.sls``` in the ```pillar``` as well and looks like it's working.
Please kindly check if it isn't the case.

Thanks - Budi

[swpm_unattended_29Apr.zip](https://github.com/SUSE/ha-sap-terraform-deployments/files/6395756/swpm_unattended_29Apr.zip)

**Comment by ab-mohamed** [comment] 2021-04-29 06:23
@arbulu89: A side note, I tried to log in to the HANA database using the `SYSTEM` user, but it did not work until I defined the database container


```
prdadm@demo1-hana01:/usr/sap/PRD/HDB00> hdbsql -n localhost -i 00 -u SYSTEM -p <PASSWORD>
* 10: authentication failed SQLSTATE: 28000
```

```
prdadm@demo1-hana01:/usr/sap/PRD/HDB00> hdbsql -d SYSTEMDB -n localhost -i 00 -u SYSTEM -p <PASSWORD>

Welcome to the SAP HANA Database interactive terminal.
                                           
Type:  \h for help with commands          
       \q to quit                         

hdbsql SYSTEMDB=> \s
host          : localhost:30013
sid           : PRD
dbname        : SYSTEMDB
user          : SYSTEM
kernel version: 2.00.052.00.1599235305
SQLDBC version:        libSQLDBCHDB 2.05.106.1597087965
autocommit    : ON
locale        : C.UTF-8
input encoding: UTF8
sql port      : demo1-hana01:30013
```

Could it be the reason behind the current issue?

**Comment by arbulu89** [comment] 2021-04-29 06:26
Hi @busetde , @ab-mohamed 

There is a failure in the HANA server while the next command is executed:
`/usr/sap/HDB/HDB00/HDBSettings.sh /usr/sap/HDB/HDB00/backup/data/DB_HDB/p_download_and_unzip.py`

This command is executed from `netweaver03` remotely in `hana01`.
Maybe you can access to `hana01` machine and excute this command (most probably with the sidadm user) and check what happens. Maybe it throws more error logs. I cannot say more... More there is not enough space on the disk to extract all of these files (just the first random thought which came to my mind)

**Comment by busetde** [comment] 2021-04-29 12:18
Hi @arbulu89 ,

Try to run the command but there's no ```p_download_and_unzip.py```
Any advise?

![image](https://user-images.githubusercontent.com/63712632/116549373-97281980-a91f-11eb-95c4-9bf34ea1f6e2.png)

Regards - Budi

**Comment by busetde** [comment] 2021-04-29 12:18
Hi @arbulu89 ,

Try to run the command but there's no ```p_download_and_unzip.py```
Any advise?

![image](https://user-images.githubusercontent.com/63712632/116549373-97281980-a91f-11eb-95c4-9bf34ea1f6e2.png)

Regards - Budi

**Comment by ab-mohamed** [comment] 2021-04-30 08:20
> Hey @ab-mohamed ,
> I found this in the logs:
> 
> ```
> Checking input element 'masterPwd': Value 'xxxxxxxx' is shorter than 10 characters.
> ```
> 
> Could you try with a 10 chars long password?
> I don't know when they added this constraint, but this is what the logs report...
> 
> More info:
> 
> ```
> TRACE      2021-04-22 12:45:46.581 (root/sapinst) (startInstallation) [DarkModeDialog.cpp:89] DarkModeDialog::submit()
> <dialog sid="d_nw_masterpassword">
> <title>Master Password</title>
> <password sid="masterPwd" confirm="true" highlight="false" enabled="true">
>  <caption>Password for All Users</caption>
>  <helpitem id="common.MasterPassword"/>
>  <encrvalue maxlength="14" minlength="10">*****</encrvalue>
> </password>
> </dialog>
> ```

I have created `https://github.com/SUSE/ha-sap-terraform-deployments/pull/689` PR for this part.

**Comment by ab-mohamed** [comment] 2021-04-30 08:23
> Hi @arbulu89 ,
> 
> Try to run the command but there's no `p_download_and_unzip.py`
> Any advise?
> 
> ![image](https://user-images.githubusercontent.com/63712632/116549373-97281980-a91f-11eb-95c4-9bf34ea1f6e2.png)
> 
> Regards - Budi

@busetde Because it was overridden. I will share an important update this afternoon. Please please stay tuned. :) 

Best regards,
Ab

**Comment by busetde** [comment] 2021-05-01 07:26
Hi @ab-mohamed,

Deplyoment is succesful after changing the disk size per instruction.
For HANA is the same there's incorrect implementation of floating IP (should be gcp-vpc-move-route)
But there's message when checking on the netweaver01 as below:
![image](https://user-images.githubusercontent.com/63712632/116774789-1f75fe00-aa89-11eb-850d-d256bd5e7375.png)

And there's message when checking on the netweaver03 as below:
![image](https://user-images.githubusercontent.com/63712632/116774796-31f03780-aa89-11eb-8b47-764d2edd31de.png)

Is the above message normal?


Thanks - Budi

**Comment by arbulu89** [comment] 2021-05-04 06:20
Hi @busetde ,

Yes `netweaver03` and `netweaver04` are not clustered.
All of the issues are already fixed in `develop` branch.

They will be available soon in a new `7.2.0` release

**Comment by ab-mohamed** [comment] 2021-05-05 11:13
@busetde: I managed to complete the deployment successfully by doing the following:
1. Using the `develop` branch.
2. I used the bastion host server option.
3. I enabled the `gcp-vpc-move-route` RA by setting `hana_cluster_vip_mechanism = "route"` in the `terraform.tfvars` file. 

HANA HA cluster used the `ocf::heartbeat:gcp-vpc-move-route` RA. 
I know that @arbulu89 is working to release `v7.2.0` that you can use. 

Please try it once it is released and let us know the results. 

Best regards,
Ab

**Comment by arbulu89** [comment] 2021-05-05 12:39
Fixed in: https://github.com/SUSE/ha-sap-terraform-deployments/releases/tag/7.2.0

**Closed by arbulu89** 2021-05-05 12:39 UTC
Labels: bug

**Comment by busetde** [comment] 2021-05-05 15:26
@ab-mohamed and @arbulu89,

Confirmed that 7.2.0 deployment is successful with S/4HANA 1909

Regards - Budi
