### ISSUE TITLE
python3.6 is needed for hanadb_exporter but not available by default on SLE12

### ISSUE THREAD

**Issue by ldevulder** [SUSE/ha-sap-terraform-deployments#199] opened 2019-09-25 09:07 UTC
The last issue we are facing is that `hanadb_exporter` requires `python3.6` and this version is not installed by default on 12-SP5 PC images (and should not also on 12-SP4), and it's not possible to install it, as this OS is not available on SCC during Build Validation.

As `python3.6` will be available in SCC after release of 12-SP5, it will be easy for customers to install it after registration or this can be done by the Salt part, but definitely not during Build Validation.

**Comment by juadk** [comment] 2019-09-25 09:11
Some traces taken this morning with qa_mode = true:
```
----------
          ID: hanadb_exporter
    Function: pkg.installed
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "An error was encountered while installing package(s): Zypper command failure: Check Zypper's logs."
              Attempt 2: Returned a result of "False", with the following comment: "An error was encountered while installing package(s): Zypper command failure: Check Zypper's logs."
              An error was encountered while installing package(s): Zypper command failure: Check Zypper's logs.
     Started: 06:44:42.639353
    Duration: 32137.84 ms
     Changes:   
----------
          ID: python3-PyHDB
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: python3-PyHDB
     Started: 06:45:14.806337
    Duration: 3115.107 ms
     Changes:   
              ----------
              python3-PyHDB:
                  ----------
                  new:
                      0.3.5.dev-1.1
                  old:
----------
          ID: configure_exporter_prd_00
    Function: file.managed
        Name: /etc/hanadb_exporter/prd_00.json
      Result: False
     Comment: One or more requisite failed: hana.exporter.hanadb_exporter
     Started: 06:45:18.002291
    Duration: 0.015 ms
     Changes:   
----------
          ID: start_exporter_prd_00
    Function: service.running
        Name: hanadb_exporter@prd_00
      Result: False
     Comment: One or more requisite failed: hana.exporter.configure_exporter_prd_00
     Started: 06:45:20.610060
    Duration: 0.016 ms
     Changes:   
```
and 
```
zypper in hanadb_exporter
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides python(abi) = 3.6 needed by hanadb_exporter-0.3.3-1.1.noarch
 Solution 1: do not install hanadb_exporter-0.3.3-1.1.noarch
 Solution 2: break hanadb_exporter-0.3.3-1.1.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): c

hana01:~ # python
python      python2     python2.7   python3     python3.4   python3.4m
```

**Comment by MalloZup** [comment] 2019-09-25 10:17
What is the python version avail in such hosts?

**Comment by juadk** [comment] 2019-09-25 10:19
> What is the python version avail in such hosts?
It's just above: python2.7 and python3.4

**Comment by diegoakechi** [comment] 2019-09-25 11:30
@ldevulder @juadk Python 3.6 was included on the DVD but with a different package name `python36` via jsc#SLE-6975. Even though, it should provide the python(abi) = 3.6 IMHO. Please, check if this package exists inside the image. If it is there, the fact that the dependency is not being resolved automatically sounds as a bug on my POV, so you guys should report it.

**Comment by juadk** [comment] 2019-09-25 14:09
> @ldevulder @juadk Python 3.6 was included on the DVD but with a different package name `python36` via jsc#SLE-6975. Even though, it should provide the python(abi) = 3.6 IMHO. Please, check if this package exists inside the image. If it is there, the fact that the dependency is not being resolved automatically sounds as a bug on my POV, so you guys should report it.
> 
> This does not solve the problem for SLE-12-SP3 or SLE-12-SP4, so I think we would need to evaluate if the `hanadb_exporter` could be executed based on py3.4 or py2.7.

I didn't see python36 included on the DVD this morning, so I guess it's not a dependency issue from your side.
```
jadamek-hana01:~ # zypper se python36
Loading repository data...
Reading installed packages...
No matching items found.
```

**Comment by arbulu89** [comment] 2019-09-27 09:38
@juadk This piece of code of salt states should be only executed if the monitoring is enabled. Right now, as we have disabled that by default, you shouldn't have that issues. Can you confirm this?

**Comment by juadk** [comment] 2019-09-27 09:41
> @juadk This piece of code of salt states should be only executed if the monitoring is enabled. Right now, as we have disabled that by default, you shouldn't have that issues. Can you confirm this?

Yes I don't have this issue anymore if `monitoring_enabled` is set to `false`. Thx

**Comment by arbulu89** [comment] 2019-09-30 10:01
The issue comes because we have hardcoded the monitoring repository to use `SLE15` which tries to use `python 3.6` instead of `python 3.4`. I will fix this issue

**Comment by juadk** [comment] 2019-09-30 10:58
> The issue comes because we have hardcoded the monitoring repository to use `SLE15` which tries to use `python 3.6` instead of `python 3.4`. I will fix this issue

Thanks for the heads up!

**Comment by arbulu89** [comment] 2019-09-30 15:32
@juadk @ldevulder Closing! The issue is fixed after the last PR merge

**Closed by arbulu89** 2019-09-30 15:32 UTC
Labels: bug, release
